fetch day:
  aoc --session-file .adventofcode.session --input-file "inputs/day{{day}}.txt" --puzzle-file "puzzles/day{{day}}.txt" --day {{day}} --year 2023 download

summarize_bench:
  python summarize_bench.py
